In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [15]:
import numpy
n=numpy.arange(27)

In [16]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [18]:
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [20]:
type(m)

numpy.ndarray

In [21]:
import cv2

In [43]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [44]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [46]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [50]:
im_g[2,4]

182

In [52]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [54]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [55]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [64]:
ims=numpy.vstack((im_g,im_g,im_g))

In [65]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [63]:
for i in ims:
    print(i)

[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
[198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
[209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]


In [72]:
lst=numpy.vsplit(ims,3)

In [75]:
type(lst)

list

In [86]:
lst[0:1]

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]